<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitde905d78242e61cf8cfb4101c29d7ace
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitde905d78242e61cf8cfb4101c29d7ace::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitde905d78242e61cf8cfb4101c29d7ace::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitde905d78242e61cf8cfb4101c29d7ace::$classMap;

        }, null, ClassLoader::class);
    }
}
